name: SSecurity Scans

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.3.45
        with:
          project_name: 'cx-devsecops/payment-service-testbed'
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          branch: ${{ github.ref }}
          scan_params: '--threshold sscs-secret-detection-critical=1 sscs-secret-detection-high=1'